#!/usr/bin/env python3
"""Resolve GTACars vehicle photos for the week's spotlight cars.

For each spotlight vehicle (podium, prize ride, premium test ride, free claim)
this resolves the GTACars slug from ``vehicle_gtacars_slugs.json``, fetches the
vehicle page, reads its ``og:image`` meta tag, and writes an absolute image URL
into ``data/references/vehicle_images.json``. The pixel dashboard generator
reads that cache to embed polaroid photos — generation itself stays offline.

Uses only the Python standard library. ``--dry-run`` resolves slugs and prints
targets without any HTTP or file writes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SLUG_MAP = ROOT / "data" / "references" / "vehicle_gtacars_slugs.json"
DEFAULT_OUTPUT = ROOT / "data" / "references" / "vehicle_images.json"
DEFAULT_DATA_DIR = ROOT / "data"
GTACARS_BASE = "https://gtacars.net"
USER_AGENT = "gta-weekly-agency/1.0 (+vehicle image cache)"

# Spotlight event names whose ``vehicle`` is worth a photo (case-insensitive).
SPOTLIGHT_EVENTS = {
    "podium vehicle",
    "prize ride challenge",
    "premium test ride",
    "free business claim",
}


def load_slug_map(path: Path) -> dict[str, str]:
    raw = json.loads(path.read_text(encoding="utf-8-sig"))
    return raw.get("slug_by_vehicle_name", raw)


def find_latest_weekly_payload(data_dir: Path) -> Path | None:
    candidates = sorted(data_dir.glob("weekly_planning_*.json"))
    return candidates[-1] if candidates else None


def spotlight_vehicles(payload: dict) -> list[str]:
    events = payload.get("weekly_content", {}).get("events", [])
    names: list[str] = []
    for event in events:
        if not isinstance(event, dict):
            continue
        if str(event.get("name", "")).casefold() in SPOTLIGHT_EVENTS:
            vehicle = event.get("vehicle")
            if isinstance(vehicle, str) and vehicle.strip():
                names.append(vehicle.strip())
    # Preserve order, drop duplicates.
    return list(dict.fromkeys(names))


def extract_og_image(html_text: str) -> str | None:
    match = re.search(
        r'<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']+)["\']',
        html_text,
        flags=re.I,
    )
    if not match:
        match = re.search(
            r'<meta[^>]+content=["\']([^"\']+)["\'][^>]+property=["\']og:image["\']',
            html_text,
            flags=re.I,
        )
    if not match:
        return None
    src = match.group(1).strip()
    if src.startswith("http"):
        return src
    return f"{GTACARS_BASE}/{src.lstrip('/')}"


def fetch_image_url(slug: str, timeout: int) -> str | None:
    url = f"{GTACARS_BASE}/gta5/{slug}"
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        body = response.read().decode("utf-8", errors="replace")
    return extract_og_image(body)


def write_cache(path: Path, images: dict[str, str], dry_run: bool) -> None:
    payload = {
        "description": (
            "vehicle_name -> absolute GTACars og:image URL for spotlight cars. "
            "Generated by scripts/fetch_vehicle_images.py; consumed by the pixel "
            "dashboard to embed polaroid photos."
        ),
        "schema_version": "1.0",
        "image_by_vehicle_name": dict(sorted(images.items(), key=lambda kv: kv[0].lower())),
    }
    if dry_run:
        print(f"[dry-run] would write {len(images)} image URLs to {path}")
        return
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"updated vehicle images: {path} ({len(images)} entries)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--weekly", type=Path, help="Specific weekly_planning_*.json (default: latest)")
    parser.add_argument("--slug-map", type=Path, default=DEFAULT_SLUG_MAP)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--timeout", type=int, default=20)
    parser.add_argument("--dry-run", action="store_true", help="Resolve slugs and print targets only")
    parser.add_argument(
        "--fail-on-missing",
        action="store_true",
        help="Exit non-zero if any spotlight vehicle could not be resolved.",
    )
    args = parser.parse_args(argv)

    weekly_path = args.weekly or find_latest_weekly_payload(DEFAULT_DATA_DIR)
    if not weekly_path or not weekly_path.exists():
        print("error: no weekly payload found", file=sys.stderr)
        return 2

    payload = json.loads(weekly_path.read_text(encoding="utf-8"))
    slug_map = load_slug_map(args.slug_map)
    vehicles = spotlight_vehicles(payload)
    if not vehicles:
        print(f"no spotlight vehicles in {weekly_path.name}; nothing to do")
        return 0

    # Start from any existing cache so older weeks' photos are kept.
    images: dict[str, str] = {}
    if args.output.exists():
        try:
            existing = json.loads(args.output.read_text(encoding="utf-8"))
            images.update(existing.get("image_by_vehicle_name", {}))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warning: could not read existing cache {args.output}: {exc}", file=sys.stderr)

    missing: list[str] = []
    for name in vehicles:
        slug = slug_map.get(name)
        if not slug:
            print(f"  - {name}: no slug in map, skipped", file=sys.stderr)
            missing.append(name)
            continue
        if args.dry_run:
            print(f"  [dry-run] {name} -> {GTACARS_BASE}/gta5/{slug}")
            continue
        try:
            image_url = fetch_image_url(slug, args.timeout)
        except (urllib.error.URLError, TimeoutError) as exc:
            print(f"  - {name} ({slug}): fetch failed: {exc}", file=sys.stderr)
            missing.append(name)
            continue
        if not image_url:
            print(f"  - {name} ({slug}): no og:image found", file=sys.stderr)
            missing.append(name)
            continue
        images[name] = image_url
        print(f"  + {name} -> {image_url}")

    if not args.dry_run:
        write_cache(args.output, images, dry_run=False)

    if missing and args.fail_on_missing:
        print(f"error: {len(missing)} spotlight vehicle(s) unresolved", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
